/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MengramPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/mengram-client.ts
var import_obsidian = require("obsidian");
var MengramError = class extends Error {
  constructor(message, statusCode) {
    super(message);
    this.name = "MengramError";
    this.statusCode = statusCode;
  }
};
var MengramClient = class {
  constructor(apiKey, options = {}) {
    if (!apiKey)
      throw new Error("API key is required");
    this.apiKey = apiKey;
    this.baseUrl = (options.baseUrl || "https://mengram.io").replace(/\/$/, "");
    this.timeout = options.timeout || 3e4;
  }
  async _request(method, path, body, params) {
    let url = `${this.baseUrl}${path}`;
    if (params) {
      const qs = Object.entries(params).filter(([, v]) => v !== void 0 && v !== null).map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(v)}`).join("&");
      if (qs)
        url += `?${qs}`;
    }
    const headers = {
      "Authorization": `Bearer ${this.apiKey}`,
      "Content-Type": "application/json"
    };
    let lastErr = null;
    for (let attempt = 0; attempt < 3; attempt++) {
      try {
        const response = await (0, import_obsidian.requestUrl)({
          url,
          method,
          headers,
          body: body ? JSON.stringify(body) : void 0,
          throw: false
        });
        const data = response.json;
        if (response.status >= 400) {
          if ([429, 502, 503, 504].includes(response.status) && attempt < 2) {
            lastErr = new MengramError(data.detail || `HTTP ${response.status}`, response.status);
            await new Promise((r) => setTimeout(r, 1e3 * (attempt + 1)));
            continue;
          }
          throw new MengramError(data.detail || `HTTP ${response.status}`, response.status);
        }
        return data;
      } catch (err) {
        const error = err instanceof Error ? err : new Error(String(err));
        if (error instanceof MengramError) {
          if ([429, 502, 503, 504].includes(error.statusCode) && attempt < 2) {
            lastErr = error;
            await new Promise((r) => setTimeout(r, 1e3 * (attempt + 1)));
            continue;
          }
          throw error;
        }
        if (attempt < 2) {
          lastErr = error;
          await new Promise((r) => setTimeout(r, 1e3 * (attempt + 1)));
          continue;
        }
        throw new MengramError(error.message, 0);
      }
    }
    throw lastErr || new MengramError("Request failed after 3 attempts", 0);
  }
  async addText(text, options = {}) {
    const data = await this._request("POST", "/v1/add_text", {
      text,
      user_id: options.userId || "default"
    });
    return data;
  }
  async search(query, options = {}) {
    const data = await this._request("POST", "/v1/search", {
      query,
      user_id: options.userId || "default",
      limit: options.limit || 10
    });
    return data.results || [];
  }
  async stats(options = {}) {
    const params = {};
    if (options.userId && options.userId !== "default") {
      params.sub_user_id = options.userId;
    }
    const data = await this._request("GET", "/v1/stats", void 0, params);
    return data;
  }
  async waitForJob(jobId, options = {}) {
    const interval = options.pollInterval || 1500;
    const maxWait = options.maxWait || 6e4;
    const start = Date.now();
    while (Date.now() - start < maxWait) {
      const job = await this._request("GET", `/v1/jobs/${jobId}`);
      if (job.status === "completed" || job.status === "failed") {
        return job;
      }
      await new Promise((r) => setTimeout(r, interval));
    }
    throw new MengramError("Job timed out", 408);
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  apiKey: "",
  autoSync: true,
  syncFolders: "",
  excludedFolders: ".trash",
  debounceMs: 2e3,
  userId: "default",
  baseUrl: "https://mengram.io"
};
var MengramSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Mengram settings").setHeading();
    new import_obsidian2.Setting(containerEl).setName("API key").setDesc("Your Mengram API key (starts with om-). Get one at mengram.io/dashboard.").addText((text) => {
      text.setPlaceholder("om-...");
      text.setValue(this.plugin.settings.apiKey);
      text.inputEl.type = "password";
      text.onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.saveSettings();
        this.plugin.reinitClient();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Auto-sync on save").setDesc("Automatically sync notes to Mengram when you save them.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoSync).onChange(async (value) => {
      this.plugin.settings.autoSync = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Sync folders").setDesc("Only sync notes in these folders (comma-separated). Leave empty to sync all.").addText((text) => text.setPlaceholder("notes,projects,journal").setValue(this.plugin.settings.syncFolders).onChange(async (value) => {
      this.plugin.settings.syncFolders = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Excluded folders").setDesc("Never sync notes in these folders (comma-separated).").addText((text) => text.setPlaceholder(".trash,templates").setValue(this.plugin.settings.excludedFolders).onChange(async (value) => {
      this.plugin.settings.excludedFolders = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Debounce delay (seconds)").setDesc("Wait this many seconds after editing before syncing.").addSlider((slider) => slider.setLimits(1, 10, 1).setValue(this.plugin.settings.debounceMs / 1e3).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.debounceMs = value * 1e3;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("User ID").setDesc("Isolate memories per user (for multi-user setups).").addText((text) => text.setPlaceholder("default").setValue(this.plugin.settings.userId).onChange(async (value) => {
      this.plugin.settings.userId = value.trim() || "default";
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Base URL").setDesc("API base URL. Only change for self-hosted instances.").addText((text) => text.setPlaceholder("https://mengram.io").setValue(this.plugin.settings.baseUrl).onChange(async (value) => {
      this.plugin.settings.baseUrl = value.trim() || "https://mengram.io";
      await this.plugin.saveSettings();
      this.plugin.reinitClient();
    }));
  }
};

// src/sync.ts
var import_obsidian3 = require("obsidian");
var SyncEngine = class {
  constructor(vault, settings, state, statusCallback, saveState) {
    this.client = null;
    this.debounceTimers = /* @__PURE__ */ new Map();
    this.queue = [];
    this.processing = false;
    this.vault = vault;
    this.settings = settings;
    this.state = state;
    this.statusCallback = statusCallback;
    this.saveState = saveState;
    this.reinitClient();
  }
  reinitClient() {
    if (this.settings.apiKey) {
      this.client = new MengramClient(this.settings.apiKey, {
        baseUrl: this.settings.baseUrl
      });
    } else {
      this.client = null;
    }
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  shouldSync(file) {
    if (file.extension !== "md")
      return false;
    const path = file.path;
    const configDir = this.vault.configDir;
    if (path.startsWith(configDir + "/"))
      return false;
    const excluded = this.parseFolderList(this.settings.excludedFolders);
    for (const folder of excluded) {
      if (path.startsWith(folder + "/") || path === folder)
        return false;
    }
    const included = this.parseFolderList(this.settings.syncFolders);
    if (included.length > 0) {
      return included.some((folder) => path.startsWith(folder + "/"));
    }
    return true;
  }
  parseFolderList(csv) {
    return csv.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
  }
  hashContent(content) {
    let hash = 5381;
    for (let i = 0; i < content.length; i++) {
      hash = (hash << 5) + hash + content.charCodeAt(i) & 4294967295;
    }
    return hash.toString(36);
  }
  hasChanged(filePath, content) {
    const newHash = this.hashContent(content);
    const oldHash = this.state.fileHashes[filePath];
    if (oldHash === newHash)
      return false;
    this.state.fileHashes[filePath] = newHash;
    return true;
  }
  onFileModified(file) {
    if (!this.settings.autoSync)
      return;
    if (!this.client)
      return;
    if (!this.shouldSync(file))
      return;
    const existing = this.debounceTimers.get(file.path);
    if (existing)
      clearTimeout(existing);
    const timer = setTimeout(() => {
      this.debounceTimers.delete(file.path);
      this.enqueue(file);
    }, this.settings.debounceMs);
    this.debounceTimers.set(file.path, timer);
  }
  enqueue(file) {
    if (!this.queue.some((f) => f.path === file.path)) {
      this.queue.push(file);
    }
    void this.processQueue();
  }
  async processQueue() {
    if (this.processing)
      return;
    if (this.queue.length === 0)
      return;
    if (!this.client)
      return;
    this.processing = true;
    while (this.queue.length > 0) {
      const file = this.queue.shift();
      await this.syncFile(file);
    }
    this.processing = false;
    this.statusCallback("idle");
  }
  async syncFile(file) {
    if (!this.client) {
      new import_obsidian3.Notice("Mengram: no API key configured");
      return false;
    }
    try {
      const content = await this.vault.cachedRead(file);
      if (!content || content.trim().length === 0)
        return false;
      if (!this.hasChanged(file.path, content))
        return false;
      this.statusCallback("syncing");
      const textToSync = `Note: ${file.basename}

${content}`;
      await this.client.addText(textToSync, {
        userId: this.settings.userId
      });
      await this.saveState();
      this.statusCallback("synced");
      return true;
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err));
      console.error(`Mengram: failed to sync ${file.path}:`, error);
      delete this.state.fileHashes[file.path];
      this.statusCallback("error");
      new import_obsidian3.Notice(`Mengram: sync failed for ${file.basename}: ${error.message}`);
      return false;
    }
  }
  async syncVault() {
    if (!this.client) {
      new import_obsidian3.Notice("Mengram: no API key configured");
      return { synced: 0, skipped: 0, errors: 0 };
    }
    const files = this.vault.getMarkdownFiles().filter((f) => this.shouldSync(f));
    const total = files.length;
    let synced = 0;
    let skipped = 0;
    let errors = 0;
    for (let i = 0; i < files.length; i++) {
      const file = files[i];
      this.statusCallback(`syncing ${i + 1}/${total}`);
      try {
        const content = await this.vault.cachedRead(file);
        if (!content || content.trim().length === 0) {
          skipped++;
          continue;
        }
        if (!this.hasChanged(file.path, content)) {
          skipped++;
          continue;
        }
        const textToSync = `Note: ${file.basename}

${content}`;
        await this.client.addText(textToSync, {
          userId: this.settings.userId
        });
        synced++;
        if (synced % 10 === 0) {
          await this.saveState();
        }
        await new Promise((r) => setTimeout(r, 200));
      } catch (err) {
        const error = err instanceof Error ? err : new Error(String(err));
        console.error(`Mengram: failed to sync ${file.path}:`, error);
        delete this.state.fileHashes[file.path];
        errors++;
      }
    }
    await this.saveState();
    this.statusCallback("idle");
    return { synced, skipped, errors };
  }
  destroy() {
    for (const timer of this.debounceTimers.values()) {
      clearTimeout(timer);
    }
    this.debounceTimers.clear();
    this.queue = [];
  }
};

// src/search-modal.ts
var import_obsidian4 = require("obsidian");
var MengramSearchModal = class extends import_obsidian4.Modal {
  constructor(app, client, userId) {
    super(app);
    this.searchTimeout = null;
    this.client = client;
    this.userId = userId;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("mengram-search-modal");
    contentEl.createEl("h2", { text: "Search memories" });
    const inputContainer = contentEl.createDiv({ cls: "mengram-search-input-container" });
    this.inputEl = inputContainer.createEl("input", {
      type: "text",
      placeholder: "Search your memories...",
      cls: "mengram-search-input"
    });
    this.inputEl.focus();
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        void this.doSearch(this.inputEl.value);
      }
    });
    this.inputEl.addEventListener("input", () => {
      if (this.searchTimeout)
        clearTimeout(this.searchTimeout);
      this.searchTimeout = setTimeout(() => {
        const query = this.inputEl.value.trim();
        if (query.length >= 3) {
          void this.doSearch(query);
        }
      }, 500);
    });
    this.resultsEl = contentEl.createDiv({ cls: "mengram-search-results" });
  }
  async doSearch(query) {
    if (!query.trim())
      return;
    this.resultsEl.empty();
    this.resultsEl.createEl("p", { text: "Searching...", cls: "mengram-search-loading" });
    try {
      const results = await this.client.search(query, {
        userId: this.userId,
        limit: 10
      });
      this.resultsEl.empty();
      if (results.length === 0) {
        this.resultsEl.createEl("p", {
          text: "No results found.",
          cls: "mengram-search-empty"
        });
        return;
      }
      for (const result of results) {
        this.renderResult(result);
      }
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err));
      this.resultsEl.empty();
      this.resultsEl.createEl("p", {
        text: `Search failed: ${error.message}`,
        cls: "mengram-search-error"
      });
    }
  }
  renderResult(result) {
    const card = this.resultsEl.createDiv({ cls: "mengram-result-card" });
    const header = card.createDiv({ cls: "mengram-result-header" });
    header.createEl("span", { text: result.entity, cls: "mengram-result-entity" });
    header.createEl("span", { text: result.type, cls: "mengram-result-type" });
    header.createEl("span", {
      text: `${Math.round(result.score * 100)}%`,
      cls: "mengram-result-score"
    });
    if (result.facts && result.facts.length > 0) {
      const factsList = card.createEl("ul", { cls: "mengram-result-facts" });
      for (const fact of result.facts.slice(0, 5)) {
        factsList.createEl("li", { text: fact });
      }
      if (result.facts.length > 5) {
        factsList.createEl("li", {
          text: `... and ${result.facts.length - 5} more`,
          cls: "mengram-result-more"
        });
      }
    }
    card.addEventListener("click", () => {
      this.insertResult(result);
    });
    card.setAttribute("title", "Click to insert into current note");
  }
  insertResult(result) {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    if (!activeView) {
      void this.createNoteFromResult(result);
      return;
    }
    const editor = activeView.editor;
    const cursor = editor.getCursor();
    const lines = [
      `## ${result.entity} (${result.type})`,
      ""
    ];
    for (const fact of result.facts) {
      lines.push(`- ${fact}`);
    }
    lines.push("");
    editor.replaceRange(lines.join("\n"), cursor);
    this.close();
  }
  async createNoteFromResult(result) {
    const lines = [
      `# ${result.entity}`,
      "",
      `**Type:** ${result.type}`,
      `**Score:** ${Math.round(result.score * 100)}%`,
      "",
      "## Facts",
      ""
    ];
    for (const fact of result.facts) {
      lines.push(`- ${fact}`);
    }
    const fileName = `${result.entity.replace(/[\\/:*?"<>|]/g, "_")}.md`;
    try {
      const file = await this.app.vault.create(fileName, lines.join("\n"));
      await this.app.workspace.openLinkText(file.path, "", true);
    } catch (e) {
      await this.app.workspace.openLinkText(fileName, "", true);
    }
    this.close();
  }
  onClose() {
    if (this.searchTimeout)
      clearTimeout(this.searchTimeout);
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
var MengramPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.client = null;
    this.syncState = { fileHashes: {} };
  }
  async onload() {
    const data = await this.loadData();
    if (data) {
      this.settings = { ...DEFAULT_SETTINGS, ...data.settings };
      this.syncState = data.syncState || { fileHashes: {} };
    }
    this.reinitClient();
    this.statusBarEl = this.addStatusBarItem();
    this.updateStatus("idle");
    this.syncEngine = new SyncEngine(
      this.app.vault,
      this.settings,
      this.syncState,
      (status) => this.updateStatus(status),
      () => this.savePluginData()
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian5.TFile) {
          this.syncEngine.onFileModified(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian5.TFile) {
          delete this.syncState.fileHashes[file.path];
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian5.TFile && this.syncState.fileHashes[oldPath]) {
          this.syncState.fileHashes[file.path] = this.syncState.fileHashes[oldPath];
          delete this.syncState.fileHashes[oldPath];
        }
      })
    );
    this.addCommand({
      id: "search-memories",
      name: "Search memories",
      callback: () => {
        if (!this.client) {
          new import_obsidian5.Notice("Mengram: please configure your API key in settings");
          return;
        }
        new MengramSearchModal(
          this.app,
          this.client,
          this.settings.userId
        ).open();
      }
    });
    this.addCommand({
      id: "sync-current-file",
      name: "Sync current file",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file && file.extension === "md") {
          if (!checking) {
            void this.syncCurrentFile(file);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "sync-vault",
      name: "Sync entire vault",
      callback: () => void this.syncVault()
    });
    this.addCommand({
      id: "show-stats",
      name: "Show memory stats",
      callback: () => void this.showStats()
    });
    this.addSettingTab(new MengramSettingTab(this.app, this));
  }
  onunload() {
    var _a;
    (_a = this.syncEngine) == null ? void 0 : _a.destroy();
  }
  reinitClient() {
    var _a;
    if (this.settings.apiKey) {
      this.client = new MengramClient(this.settings.apiKey, {
        baseUrl: this.settings.baseUrl
      });
    } else {
      this.client = null;
    }
    (_a = this.syncEngine) == null ? void 0 : _a.reinitClient();
  }
  async saveSettings() {
    var _a;
    (_a = this.syncEngine) == null ? void 0 : _a.updateSettings(this.settings);
    await this.savePluginData();
  }
  async savePluginData() {
    await this.saveData({
      settings: this.settings,
      syncState: this.syncState
    });
  }
  updateStatus(status) {
    const display = {
      idle: "Mengram: idle",
      syncing: "Mengram: syncing...",
      synced: "Mengram: synced",
      error: "Mengram: error"
    };
    if (status.startsWith("syncing ")) {
      this.statusBarEl.setText(`Mengram: ${status}`);
      return;
    }
    this.statusBarEl.setText(display[status] || `Mengram: ${status}`);
    if (status === "synced") {
      setTimeout(() => {
        if (this.statusBarEl.getText() === "Mengram: synced") {
          this.statusBarEl.setText("Mengram: idle");
        }
      }, 3e3);
    }
  }
  async syncCurrentFile(file) {
    if (!this.client) {
      new import_obsidian5.Notice("Mengram: please configure your API key in settings");
      return;
    }
    new import_obsidian5.Notice(`Mengram: syncing ${file.basename}...`);
    const success = await this.syncEngine.syncFile(file);
    if (success) {
      new import_obsidian5.Notice(`Mengram: ${file.basename} synced`);
    }
  }
  async syncVault() {
    if (!this.client) {
      new import_obsidian5.Notice("Mengram: please configure your API key in settings");
      return;
    }
    new import_obsidian5.Notice("Mengram: starting vault sync...");
    const result = await this.syncEngine.syncVault();
    new import_obsidian5.Notice(
      `Mengram: vault sync complete. Synced: ${result.synced}, skipped: ${result.skipped}, errors: ${result.errors}`
    );
  }
  async showStats() {
    if (!this.client) {
      new import_obsidian5.Notice("Mengram: please configure your API key in settings");
      return;
    }
    try {
      const stats = await this.client.stats({ userId: this.settings.userId });
      new import_obsidian5.Notice(
        `Mengram stats:
Entities: ${stats.entities}
Facts: ${stats.facts}
Knowledge: ${stats.knowledge}
Relations: ${stats.relations}`,
        1e4
      );
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err));
      new import_obsidian5.Notice(`Mengram: failed to get stats: ${error.message}`);
    }
  }
};
